project:
  type: website

theme:
  light: flatly
  dark: darkly


website:
  sidebar:
    search: true
    tools:
      - icon: cloud
        href: https://northeastern-my.sharepoint.com/:f:/g/personal/r_herron_northeastern_edu/ElSKCp7KsodKq21d2ydTIL8BIaha56J0VxUm7CxObo-wVA?e=1s8bB8
      - icon: github
        href: https://github.com/richard-herron/fina-6333-2025-spring
      - icon: google
        url: https://colab.research.google.com/github/richard-herron/fina-6333-2025-spring
    collapse-level: 1
    contents:
      - index.qmd
      - section: Week 1
        contents: 
          - auto: "mckinney_02*.ipynb"
      - section: Week 2
        contents: 
          - auto: "mckinney_03*.ipynb"
      - section: Week 3
        contents: 
          - auto: "mckinney_04*.ipynb"
      - section: Week 4
        contents: 
          - auto: "mckinney_05*.ipynb"
      - section: Week 5
        contents: 
          - auto: "mckinney_08*.ipynb"
          - auto: "herron_01*.ipynb"
      - section: Week 6
        contents: 
          - auto: "mckinney_10*.ipynb"
      - section: Week 7
        contents: 
          - auto: "mckinney_11*.ipynb"
      - section: Week 8
        contents:
          - "../Projects/Project 1/project_1.ipynb"
      - section: Week 9
        contents: 
          - auto: "herron_02*.ipynb"
      - section: Week 10
        contents: 
          - auto: "herron_03*.ipynb"
      - section: Week 11
        contents: 
          - "../Projects/Project 2/project_2.ipynb"
      - section: Week 12
        contents: 
          - students_choice_03.qmd
      - section: Week 13
        contents: 
          - students_choice_04.qmd
      - section: Week 14
        contents: 
          - assessment_exam.qmd
      - section: Week 15
        contents: 
          - project_03.qmd
